/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function parseLoglineStr(input: string): string
export declare function serializeLoglineJson(json: string): string
/** Request to translate natural language to LogLine */
export interface TranslateRequest {
  text: string
  grammarPath?: string
}
/** Result of translation */
export interface TranslateResult {
  verdict: string
  spanJson?: string
  confidence: number
  mode?: string
  abstainReason?: string
  clarification?: string
  suggestions?: Array<string>
  truthPackJson?: string
}
/** Translate natural language to LogLine span */
export declare function translateNlToLogline(req: TranslateRequest): TranslateResult
/** Legacy function for backwards compatibility */
export declare function compileIntent(text: string, grammarPath: string): string
/** Request to render structured data to natural language */
export interface RenderRequest {
  templateName: string
  dataJson: string
  templatesPath?: string
}
/** Result of rendering */
export interface RenderResult {
  output: string
  templateUsed: string
  citationsJson: string
  valid: boolean
}
/** Render structured data to natural language using a named template */
export declare function renderToNaturalLanguage(req: RenderRequest): RenderResult
/** Render using an inline template string */
export declare function renderTemplateString(template: string, dataJson: string): string
/** Legacy function for backwards compatibility */
export declare function renderJsonToNl(json: string, templatePath: string): string
/** Quick render helpers */
export declare function quickJobSuccess(summary: string, changesJson?: string | undefined | null, testsJson?: string | undefined | null): string
export declare function quickJobFailure(reason: string, error?: string | undefined | null): string
export declare function quickClarification(question: string, suggestions: Array<string>): string
export declare function version(): string
