ALTER TABLE jobs
  ADD COLUMN IF NOT EXISTS step_cap INTEGER DEFAULT 20,
  ADD COLUMN IF NOT EXISTS steps_used INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS token_cap INTEGER DEFAULT 100000,
  ADD COLUMN IF NOT EXISTS tokens_used INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS cost_cap_cents INTEGER DEFAULT 1000,
  ADD COLUMN IF NOT EXISTS cost_used_cents INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS current_action TEXT;
